#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "embedder.h"
#include "utils.h"

/* =========================
   OPTIONS
========================= */

EmbedderOptions* embedder_options_new(void)
{
    EmbedderOptions* opts = malloc(sizeof(EmbedderOptions));
    if (!opts) return NULL;

    memset(opts->lua_code, 0, sizeof(opts->lua_code));
    memset(opts->output_file, 0, sizeof(opts->output_file));
    memset(opts->icon_file, 0, sizeof(opts->icon_file));
    memset(opts->version, 0, sizeof(opts->version));
    opts->console_mode = 0;

    return opts;
}

void embedder_options_free(EmbedderOptions* opts)
{
    if (opts) free(opts);
}

/* =========================
   READ LUA BYTECODE FILE
   (.luac)
========================= */

int embedder_read_lua_file(const char* filename, char* buffer, size_t buffer_size)
{
    FILE* f;
    size_t bytes_read;

    f = fopen(filename, "rb");
    if (!f) {
        error_print("Failed to open file: %s\n", filename);
        return 1;
    }

    bytes_read = fread(buffer, 1, buffer_size, f);

    if (ferror(f)) {
        error_print("Failed to read file: %s\n", filename);
        fclose(f);
        return 1;
    }

    fclose(f);

    if (bytes_read == buffer_size) {
        error_print("Warning: file truncated (buffer too small)\n");
    }

    /* store size in first bytes (simple hack) */
    ((size_t*)buffer)[0] = bytes_read;

    return 0;
}

/* =========================
   GENERATE C SOURCE (BYTECODE)
========================= */

int embedder_generate_source(EmbedderOptions* opts, const char* output_source)
{
    FILE* f;
    const unsigned char* bytecode;
    size_t bytecode_size;

    f = fopen(output_source, "w");
    if (!f) {
        error_print("Failed to create output source file: %s\n", output_source);
        return 1;
    }

    /* bytecode is stored after size header */
    bytecode = (unsigned char*)opts->lua_code + sizeof(size_t);
    bytecode_size = *((size_t*)opts->lua_code);

    fprintf(f,
        "#include <stdio.h>\n"
        "#include <stdlib.h>\n"
        "#include <string.h>\n"
        "#include \"lua.h\"\n"
        "#include \"lualib.h\"\n"
        "#include \"lauxlib.h\"\n\n"
        "static const unsigned char lua_bytecode[] = {\n"
    );

    /* write byte array */
    for (size_t i = 0; i < bytecode_size; i++) {
        fprintf(f, "0x%02X,", bytecode[i]);
        if ((i + 1) % 12 == 0)
            fprintf(f, "\n");
    }

    fprintf(f,
        "\n};\n"
        "static const size_t lua_bytecode_size = sizeof(lua_bytecode);\n\n"
        "int main(int argc, char* argv[])\n"
        "{\n"
        "    lua_State* L = luaL_newstate();\n"
        "    if (!L) {\n"
        "        printf(\"Failed to create Lua state\\n\");\n"
        "        return 1;\n"
        "    }\n\n"
        "    luaL_openlibs(L);\n\n"
        "    if (luaL_loadbuffer(L, (const char*)lua_bytecode, lua_bytecode_size, \"embedded\") == 0) {\n"
        "        lua_pcall(L, 0, LUA_MULTRET, 0);\n"
        "    } else {\n"
        "        printf(\"Lua Error: %%s\\n\", lua_tostring(L, -1));\n"
        "    }\n\n"
        "    lua_close(L);\n"
        "    return 0;\n"
        "}\n"
    );

    fclose(f);

    info_print("Generated bytecode-based C source: %s\n", output_source);
    return 0;
}

/* =========================
   COMPILE STEP (UNCHANGED)
========================= */

int embedder_compile_source(const char* source_file, const char* output_file,
                           const char* icon_file, int console_mode)
{
    char command[2048];
    int result;

#ifdef _WIN32
    const char* compiler = "gcc";
    const char* lua_include = "C:/Users/Saar/scoop/apps/lua/current/include";
    const char* lua_lib = "C:/Users/Saar/scoop/apps/lua/current/lib";
    const char* console_flag = console_mode ? "-mconsole" : "-mwindows";

    snprintf(command, sizeof(command),
        "%s -o %s %s -I%s -L%s %s -llua -lm -Wall -Wextra",
        compiler, output_file, source_file,
        lua_include, lua_lib, console_flag);
#else
    snprintf(command, sizeof(command),
        "gcc -o %s %s -llua -lm -Wall -Wextra",
        output_file, source_file);
#endif

    info_print("Executing: %s\n", command);
    result = system(command);

    if (result == 0) {
        info_print("Successfully created executable: %s\n", output_file);
    } else {
        error_print("Compilation failed with exit code: %d\n", result);
    }

    return result;
}
